In [1]:
import numpy as np
import pandas as pd

#### Question 1

In [2]:
np.__version__

'1.20.3'

#### Question 2

In [3]:
pd.__version__

'1.2.4'

#### Question 3

In [4]:
cars = pd.read_csv('data.csv', header=0)

In [5]:
cars.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [6]:
cars[cars['Make'] == 'BMW']['MSRP'].mean()

61546.76347305389

#### Question 4

In [7]:
no_engineHP = cars.query('Year >= 2015 & `Engine HP`.isna()', engine='python')

In [8]:
len(no_engineHP)

51

#### Question 5

In [9]:
mean_HP = cars['Engine HP'].mean()

In [10]:
round(mean_HP)

249

In [11]:
cars[cars['Engine HP'].isna()] = mean_HP
new_mean_HP = cars['Engine HP'].mean()

In [12]:
round(new_mean_HP)

249

#### Question 6

In [13]:
rr_cars = cars[cars['Make'] == "Rolls-Royce"][["Engine HP", "Engine Cylinders", "highway MPG"]]
len(rr_cars)

31

In [14]:
rr_cars.head()

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0         15.0
3505      563.0              12.0         19.0
5275      563.0              12.0         21.0
5276      563.0              12.0         21.0
5277      563.0              12.0         21.0

In [15]:
rr_cars = rr_cars.drop_duplicates()
len(rr_cars)

7

In [16]:
X = rr_cars.to_numpy()
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [17]:
XTX = np.matmul(X.T, X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [18]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [19]:
inv_XTX.sum()

0.032212320677486125

#### Question 7

In [20]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [21]:
inv_XTX__XT = np.matmul(inv_XTX, X.T)

In [22]:
w = np.matmul(inv_XTX__XT, y)

In [23]:
w[0]

0.19989598183188972